name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          
          ### New Features
          - HTTP API Integration for Kostal inverters
          - Apple Home Energy Provider support (iOS 16+)
          - Multi-language support (DE, EN, FR, IT, ZH)
          - Child Bridge capability
          
          ### Technical Improvements
          - TypeScript implementation
          - Robust error handling
          - Configurable update intervals
          - Debug logging support
          
          ### HomeKit Integration
          - Energy Provider Service (iOS 16+)
          - Solar Panel Service (fallback)
          - Temperature monitoring
          - String monitoring
          
          ## Installation
          ```bash
          npm install -g homebridge-kostal-inverter
          ```
          
          ## Documentation
          See [README.md](README.md) for full configuration and usage instructions.
        draft: false
        prerelease: false
    
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
