name: Check for Updates

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for outdated packages
      run: npm outdated --json || true
      
    - name: Update dependencies
      run: |
        npm update
        npm audit fix --force
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'chore: update dependencies'
        body: |
          ## 🔄 Dependency Updates
          
          This PR updates outdated dependencies to their latest versions.
          
          ### Changes:
          - Updated npm packages to latest versions
          - Applied security fixes from npm audit
          
          ### Testing:
          - [ ] Build passes
          - [ ] Tests pass
          - [ ] Plugin functionality verified
          
        branch: dependency-updates
        delete-branch: true
        commit-message: 'chore: update dependencies'
